 
listen: :8088
username: "admin"
passwotd: "123"
etcd:
    endpoint   : [http://192.168.0.165:2379]
    path_prefix : /coredns
    timeout: 5
    #username: ""
    #password: ""
    #tls: [cert,key,ca]

